/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ResourcesImport } from './routes/resources'
import { Route as NotFoundImport } from './routes/not-found'
import { Route as MapsImport } from './routes/maps'
import { Route as DatabaseImport } from './routes/database'
import { Route as ComingSoonImport } from './routes/coming-soon'
import { Route as IndexImport } from './routes/index'
import { Route as MapTestIndexImport } from './routes/map-test/index'
import { Route as MapTestMaplibreImport } from './routes/map-test/maplibre'

// Create/Update Routes

const ResourcesRoute = ResourcesImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRoute,
} as any)

const NotFoundRoute = NotFoundImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRoute,
} as any)

const MapsRoute = MapsImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRoute,
} as any)

const DatabaseRoute = DatabaseImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => rootRoute,
} as any)

const ComingSoonRoute = ComingSoonImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MapTestIndexRoute = MapTestIndexImport.update({
  id: '/map-test/',
  path: '/map-test/',
  getParentRoute: () => rootRoute,
} as any)

const MapTestMaplibreRoute = MapTestMaplibreImport.update({
  id: '/map-test/maplibre',
  path: '/map-test/maplibre',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonImport
      parentRoute: typeof rootRoute
    }
    '/database': {
      id: '/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof DatabaseImport
      parentRoute: typeof rootRoute
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsImport
      parentRoute: typeof rootRoute
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundImport
      parentRoute: typeof rootRoute
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesImport
      parentRoute: typeof rootRoute
    }
    '/map-test/maplibre': {
      id: '/map-test/maplibre'
      path: '/map-test/maplibre'
      fullPath: '/map-test/maplibre'
      preLoaderRoute: typeof MapTestMaplibreImport
      parentRoute: typeof rootRoute
    }
    '/map-test/': {
      id: '/map-test/'
      path: '/map-test'
      fullPath: '/map-test'
      preLoaderRoute: typeof MapTestIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coming-soon': typeof ComingSoonRoute
  '/database': typeof DatabaseRoute
  '/maps': typeof MapsRoute
  '/not-found': typeof NotFoundRoute
  '/resources': typeof ResourcesRoute
  '/map-test/maplibre': typeof MapTestMaplibreRoute
  '/map-test': typeof MapTestIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coming-soon': typeof ComingSoonRoute
  '/database': typeof DatabaseRoute
  '/maps': typeof MapsRoute
  '/not-found': typeof NotFoundRoute
  '/resources': typeof ResourcesRoute
  '/map-test/maplibre': typeof MapTestMaplibreRoute
  '/map-test': typeof MapTestIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/coming-soon': typeof ComingSoonRoute
  '/database': typeof DatabaseRoute
  '/maps': typeof MapsRoute
  '/not-found': typeof NotFoundRoute
  '/resources': typeof ResourcesRoute
  '/map-test/maplibre': typeof MapTestMaplibreRoute
  '/map-test/': typeof MapTestIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coming-soon'
    | '/database'
    | '/maps'
    | '/not-found'
    | '/resources'
    | '/map-test/maplibre'
    | '/map-test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coming-soon'
    | '/database'
    | '/maps'
    | '/not-found'
    | '/resources'
    | '/map-test/maplibre'
    | '/map-test'
  id:
    | '__root__'
    | '/'
    | '/coming-soon'
    | '/database'
    | '/maps'
    | '/not-found'
    | '/resources'
    | '/map-test/maplibre'
    | '/map-test/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComingSoonRoute: typeof ComingSoonRoute
  DatabaseRoute: typeof DatabaseRoute
  MapsRoute: typeof MapsRoute
  NotFoundRoute: typeof NotFoundRoute
  ResourcesRoute: typeof ResourcesRoute
  MapTestMaplibreRoute: typeof MapTestMaplibreRoute
  MapTestIndexRoute: typeof MapTestIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComingSoonRoute: ComingSoonRoute,
  DatabaseRoute: DatabaseRoute,
  MapsRoute: MapsRoute,
  NotFoundRoute: NotFoundRoute,
  ResourcesRoute: ResourcesRoute,
  MapTestMaplibreRoute: MapTestMaplibreRoute,
  MapTestIndexRoute: MapTestIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/coming-soon",
        "/database",
        "/maps",
        "/not-found",
        "/resources",
        "/map-test/maplibre",
        "/map-test/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/coming-soon": {
      "filePath": "coming-soon.tsx"
    },
    "/database": {
      "filePath": "database.tsx"
    },
    "/maps": {
      "filePath": "maps.tsx"
    },
    "/not-found": {
      "filePath": "not-found.tsx"
    },
    "/resources": {
      "filePath": "resources.tsx"
    },
    "/map-test/maplibre": {
      "filePath": "map-test/maplibre.tsx"
    },
    "/map-test/": {
      "filePath": "map-test/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
